const state = { payload: null, model: null };
const $ = (selector) => document.querySelector(selector);
const subjectDefaults = { Maths: { present: 35, absent: 3 }, DBMS: { present: 31, absent: 5 }, AI: { present: 28, absent: 4 }, OS: { present: 34, absent: 2 } };
const timetable = { Monday: ['Maths', 'Maths', 'DBMS'], Tuesday: ['AI', 'Maths'], Wednesday: ['OS', 'Maths'], Thursday: ['DBMS', 'AI'], Friday: ['OS', 'DBMS'] };
function makePayload(requirement) { return { minimum_attendance: requirement, academic_calendar: { start_date: $('#startDate').value, end_date: $('#endDate').value }, holidays: ['2026-08-15'], special_holidays: ['2026-09-21'], working_weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], timetable, subjects: subjectDefaults, as_of_date: '2026-06-01' }; }
function setRequirement(value) { $('#minimumAttendance').value = value; $('#minimumOutput').value = value; document.querySelectorAll('[data-requirement]').forEach((button) => button.classList.toggle('selected', Number(button.dataset.requirement) === Number(value))); }
function showError(message) { $('#errorMessage').textContent = message || ''; }
function renderSubjects(data) { $('#overallRisk').textContent = `Overall risk: ${data.overall_risk}`; $('#subjectGrid').innerHTML = Object.entries(data.subjects).map(([name, subject]) => { const margin = subject.attendance_margin; const after = subject.future_attendance_after_leave; return `<article class="subject-card"><h3>${name}</h3><div class="metric"><span>Current Attendance</span><strong>${subject.attendance_percentage.toFixed(2)}%</strong></div><div class="metric"><span>Required</span><strong>${data.minimum_attendance}%</strong></div><div class="metric"><span>Margin</span><strong class="${margin >= 0 ? 'margin-positive' : 'margin-negative'}">${margin >= 0 ? '+' : ''}${margin.toFixed(2)}%</strong></div><div class="metric"><span>After Leave</span><strong>${after.toFixed(2)}%</strong></div><div class="metric"><span>Maximum Safe Leave</span><strong>${subject.maximum_safe_leave} classes</strong></div><div class="metric"><span>Risk / model probability</span><strong>${subject.risk_level} / ${(subject.probability * 100).toFixed(1)}%</strong></div><div class="metric"><span>Mathematical eligibility</span><strong class="${subject.safe_leave ? 'safe' : 'unsafe'}">${subject.safe_leave ? 'SAFE' : 'UNSAFE'}</strong></div></article>`; }).join(''); }
async function predict(requirement = Number($('#minimumAttendance').value)) { showError(''); const payload = makePayload(requirement); try { const response = await fetch('/predict-leave', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Prediction failed'); state.payload = payload; renderSubjects(data); $('#results').hidden = false; await renderComparison(); } catch (error) { showError(error.message); } }
async function renderComparison() { const requirements = [75, 80, 85, 90]; const responses = await Promise.all(requirements.map((value) => fetch('/predict-leave', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(makePayload(value)) }).then((response) => response.json()))); $('#comparisonGrid').innerHTML = responses.map((data, index) => { const safeLeave = Math.min(...Object.values(data.subjects).map((subject) => subject.maximum_safe_leave)); return `<div class="comparison-cell"><span>${requirements[index]}% requirement</span><strong>${safeLeave} classes</strong><small>${data.overall_risk} overall risk</small></div>`; }).join(''); }
function renderModel(model) { state.model = model; $('#apiStatus').textContent = `API online / ${model.model}`; $('#modelStats').innerHTML = [['Algorithm', model.model], ['Training Samples', model.training_samples.toLocaleString()], ['Accuracy', `${(model.accuracy * 100).toFixed(2)}%`], ['Precision', `${(model.precision * 100).toFixed(2)}%`], ['Recall', `${(model.recall * 100).toFixed(2)}%`], ['F1 Score', `${(model.f1_score * 100).toFixed(2)}%`]].map(([label, value]) => `<div class="stat"><span>${label}</span><strong>${value}</strong></div>`).join(''); const values = Object.entries(model.feature_importance).sort((a, b) => b[1] - a[1]); $('#featureImportance').innerHTML = `<h3>Feature Importance</h3>${values.map(([name, value]) => `<div class="bar-row"><span>${name.replaceAll('_', ' ')}</span><div class="bar"><i style="width:${value * 100}%"></i></div><strong>${(value * 100).toFixed(1)}%</strong></div>`).join('')}`; }
$('#minimumAttendance').addEventListener('input', (event) => setRequirement(event.target.value)); document.querySelectorAll('[data-requirement]').forEach((button) => button.addEventListener('click', () => { setRequirement(button.dataset.requirement); predict(Number(button.dataset.requirement)); })); $('#predictButton').addEventListener('click', () => predict()); setRequirement(75); fetch('/model-info').then((response) => response.json()).then(renderModel).catch(() => { $('#apiStatus').textContent = 'API unavailable'; });
